-- 코드를 입력하세요
SELECT B.PRODUCT_CODE,
       SUM(SALES_AMOUNT) * B.PRICE AS SALES
FROM OFFLINE_SALE A
LEFT JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SUM(SALES_AMOUNT) * B.PRICE DESC, B.PRODUCT_CODE