-- 코드를 입력하세요
SELECT car_id,
       # CASE WHEN DATE_FORMAT(end_date,'%Y-%m-%d') < '2022-10-16' THEN '대여 가능' ELSE '대여중' END AVAILABILITY
       MAX(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중' ELSE '대여 가능'END)  AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY car_id
ORDER BY car_id DESC