-- 코드를 입력하세요

SELECT A.APNT_NO,
       B.PT_NAME,
       B.PT_NO,
       A.MCDP_CD,
       C.DR_NAME,
       A.APNT_YMD
FROM APPOINTMENT A
LEFT JOIN PATIENT B ON A.PT_NO = B.PT_NO
LEFT JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE B.PT_NAME IS NOT NULL
AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d') = '2022-04-13'
AND A.APNT_CNCL_YN = 'N'
GROUP BY A.APNT_NO
ORDER BY A.APNT_YMD
