SELECT 
# A.BOOK_ID,
    B.CATEGORY, 
     # A.SALES_DATE, 
    sum(A.SALES) as sales
FROM BOOK_SALES A 
LEFT JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY